apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: estudo-jenkins
type: Opaque
stringData:
  POSTGRES_DB: produto_db
  POSTGRES_USER: produto_user
  POSTGRES_PASSWORD: produto_pass
