services:
  jenkins:
    build: .
    container_name: jenkins-local
    restart: unless-stopped
    user: root
    ports:
      - "8085:8080"
      - "50084:50000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # Windows PowerShell/Docker Desktop:
      - ${USERPROFILE}/.kube:/root/.kube:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  jenkins_home:
